# Generated by Django 5.2.4 on 2025-08-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admin_tips',
        ),
        migrations.AddField(
            model_name='student',
            name='allow',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of the test in minutes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('message_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.job')),
            ],
            options={
                'verbose_name_plural': 'Job Opportunities',
                'unique_together': {('job', 'student_email')},
            },
        ),
    ]
