# Generated by Django 5.2.4 on 2025-08-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_admin_tips_student_allow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
    ]
