# Generated by Django 5.2.4 on 2025-08-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('division_name', models.CharField(max_length=200)),
                ('aptitude_conducted', models.BooleanField(default=False)),
                ('aptitude_questions', models.TextField(blank=True, null=True)),
                ('technical_questions', models.TextField(blank=True, null=True)),
                ('hr_questions', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
