# Generated by Django 5.2.4 on 2025-08-23 18:39

import django.db.models.deletion
import interview_questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_admin_tips_student_allow_and_more'),
        ('interview_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewexperience',
            name='aptitude_attachment',
            field=models.FileField(blank=True, null=True, upload_to=interview_questions.models.interview_upload_path),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='gd_attachment',
            field=models.FileField(blank=True, null=True, upload_to=interview_questions.models.interview_upload_path),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='gd_conducted',
            field=models.BooleanField(default=False, verbose_name='Group Discussion Conducted'),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='gd_topics',
            field=models.TextField(blank=True, null=True, verbose_name='Group Discussion Topics'),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='hr_attachment',
            field=models.FileField(blank=True, null=True, upload_to=interview_questions.models.interview_upload_path),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='hr_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.job'),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='overall_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='student_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='technical_attachment',
            field=models.FileField(blank=True, null=True, upload_to=interview_questions.models.interview_upload_path),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='technical_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='tips',
            field=models.TextField(blank=True, help_text='Any tips or advice for future candidates', null=True),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
