# Generated by Django 5.2.5 on 2025-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0002_interviewexperience_aptitude_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewexperience',
            name='aptitude_attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='gd_attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='hr_attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewexperience',
            name='technical_attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
